Repository KnowckknowcK/BE, pull requests merged in 2024-04, with the labels that each got.

#38 Feat/issue #33 PR 리뷰 반영 (AI 피드백 파싱 메서드 위치 변경, Summary 엔티티에 Persistable 추가)
  build.gradle
  src/main/java/com/knu/KnowcKKnowcK/domain/Summary.java
  src/main/java/com/knu/KnowcKKnowcK/domain/SummaryFeedback.java
  src/main/java/com/knu/KnowcKKnowcK/dto/prompt/SummaryPrompt.java
  src/main/java/com/knu/KnowcKKnowcK/repository/SummaryFeedbackRepository.java
  src/main/java/com/knu/KnowcKKnowcK/repository/SummaryRepository.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/ChatGptContext.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/ChatGptService.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/ChatGptServiceTest.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/OpinionFeedbackService.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/SummaryFeedbackService.java
  src/test/java/com/knu/KnowcKKnowcK/controller/articleSummary/SaveSummaryControllerTest.java
  src/test/java/com/knu/KnowcKKnowcK/controller/articleSummary/SaveSummaryTest.java
Labels: 🔨 Refactor

#44 Feat: 문해력 진단 - 지문 견해 AI 피드백 기능
  src/main/java/com/knu/KnowcKKnowcK/domain/Opinion.java
  src/main/java/com/knu/KnowcKKnowcK/domain/OpinionFeedback.java
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/OpinionRequestDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/OpinionResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/repository/OpinionFeedbackRepository.java
  src/main/java/com/knu/KnowcKKnowcK/repository/OpinionRepository.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveOpinionService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveOpinionServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/OpinionFeedbackService.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveOpinionServiceTest.java
Labels: ✨ Feature

#45 Feat/issue #36 이메일 회원 가입, 로그인
  build.gradle
  src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java
  src/main/java/com/knu/KnowcKKnowcK/domain/Member.java
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/SigninRequestDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/SignupRequestDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SigninResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SignupResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/AccountService.java
Labels: ✨ Feature

#46 Feat/issue #34
  src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoom/DebateRoomController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoom/MessageController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoom/PubSubController.java
  src/main/java/com/knu/KnowcKKnowcK/domain/Message.java
  src/main/java/com/knu/KnowcKKnowcK/domain/MessageThread.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DebateRoomResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MessageResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MessageThreadResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/PreferenceResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/repository/PreferenceRepository.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/debateRoom/DebateRoomService.java
  src/main/java/com/knu/KnowcKKnowcK/service/debateRoom/MessageService.java
  src/test/java/com/knu/KnowcKKnowcK/controller/articleSummary/SaveSummaryTest.java
Labels: ✨ Feature

#51 Fix: `Summary` 도메인 속성 타입 변경에 맞게 수정
  src/main/java/com/knu/KnowcKKnowcK/converter/StringToScoreConverter.java
  src/main/java/com/knu/KnowcKKnowcK/domain/SummaryFeedback.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SummaryResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveOpinionServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/ChatGptContext.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/ChatGptService.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/ChatGptServiceTest.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/OpinionFeedbackService.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/SummaryFeedbackService.java
  src/test/java/com/knu/KnowcKKnowcK/controller/articleSummary/SaveSummaryTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveOpinionServiceTest.java
Labels: 🐞 BugFix, 🔨 Refactor

#48 Feat: 카테고리 별로 지문 목록 조회
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/LoadArticlesController.java
  src/main/java/com/knu/KnowcKKnowcK/repository/ArticleRepository.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceImpl.java
Labels: ✨ Feature

#61 Feat/issue #47
  src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoom/DebateRoomController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoom/PubSubController.java
  src/main/java/com/knu/KnowcKKnowcK/domain/MemberDebate.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DebateRoomMemberDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DebateRoomResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/repository/MemberDebateRepository.java
  src/main/java/com/knu/KnowcKKnowcK/service/debateRoom/DebateRoomService.java
Labels: ✨ Feature

#64 Refactor: 지문 목록 조회 페이징 처리
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/LoadArticlesController.java
  src/main/java/com/knu/KnowcKKnowcK/repository/ArticleRepository.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceImpl.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceTest.java
Labels: 🔨 Refactor

#66 Feat: 요약 작성 히스토리 로드
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/LoadArticlesController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/LoadSummaryController.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SummaryHistoryResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/enums/Status.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceImpl.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceTest.java
Labels: ✨ Feature
