Repository KnowckknowcK/BE, pull requests merged in 2024-05, with the labels that each got.

#71 Fix/issue #70
  build.gradle
  src/main/java/com/knu/KnowcKKnowcK/KnowcKKnowcKApplication.java
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/LoadSummaryController.java
  src/main/java/com/knu/KnowcKKnowcK/dto/prompt/SummaryPrompt.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/SummaryFeedbackService.java
Labels: 🐞 BugFix

#79 Feat/issue #43 요약, 견해 조회
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyDebateRoomController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyOpinionController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyProfileController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MySummaryController.java
  src/main/java/com/knu/KnowcKKnowcK/domain/Member.java
  src/main/java/com/knu/KnowcKKnowcK/domain/Opinion.java
  src/main/java/com/knu/KnowcKKnowcK/domain/Summary.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MyOpinionResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MySummaryResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/exception/ErrorCode.java
  src/main/java/com/knu/KnowcKKnowcK/repository/SummaryFeedbackRepository.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyOpinionService.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MySummaryService.java
  src/test/java/com/knu/KnowcKKnowcK/controller/myInfo/MyProfileControllerTest.java
  src/test/java/com/knu/KnowcKKnowcK/controller/myInfo/MySummaryControllerTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/myPage/MySummaryServiceTest.java
Labels: ✨ Feature

#89 Feat/issue #83 기사 to 토론방 생성 로직 추가
  build.gradle
  src/main/java/com/knu/KnowcKKnowcK/domain/DebateRoom.java
  src/main/java/com/knu/KnowcKKnowcK/exception/ErrorCode.java
  src/main/java/com/knu/KnowcKKnowcK/job/BatchJobLauncher.java
  src/main/java/com/knu/KnowcKKnowcK/job/config/DebateRoomBatchConfig.java
  src/main/java/com/knu/KnowcKKnowcK/job/step/DebateRoomWriter.java
  src/main/java/com/knu/KnowcKKnowcK/job/step/ToDebateRoomProcessor.java
  src/main/java/com/knu/KnowcKKnowcK/repository/DebateRoomRepository.java
  src/main/java/com/knu/KnowcKKnowcK/service/debateRoom/DebateRoomService.java
  src/test/java/com/knu/KnowcKKnowcK/service/debateRoom/DebateRoomServiceTest.java
Labels: ✨ Feature

#82 Feat/issue #67 JWT 구현
  build.gradle
  src/main/java/com/knu/KnowcKKnowcK/config/PasswordEncoderConfig.java
  src/main/java/com/knu/KnowcKKnowcK/config/WebSecurityConfig.java
  src/main/java/com/knu/KnowcKKnowcK/config/jwtConfig/JwtFilter.java
  src/main/java/com/knu/KnowcKKnowcK/config/jwtConfig/JwtSecurityConfig.java
  src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SigninResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SignupResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/exception/ErrorCode.java
  src/main/java/com/knu/KnowcKKnowcK/exception/jwtHandler/JwtAccessDeniedHandler.java
  src/main/java/com/knu/KnowcKKnowcK/exception/jwtHandler/JwtAuthenticationEntryPoint.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/AccountService.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/UserDetailsServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/utils/JwtUtil.java
Labels: ✨ Feature

#104 Fix: 로그인 인증 전 임시 userId 변경
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/ArticleListController.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/SummaryFeedbackService.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceTest.java
Labels: :wrench: LogicFix

#106 Fix: 인증 필요없는 api 추가
  src/main/java/com/knu/KnowcKKnowcK/config/WebSecurityConfig.java
Labels: 🐞 BugFix

#113 Refactor: 문해력 진단 부분 jwt 적용
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/OpinionController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/SummaryController.java
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/OpinionRequestDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/SummaryRequestDto.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleOpinion/SaveOpinionService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleOpinion/SaveOpinionServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java
  src/test/java/com/knu/KnowcKKnowcK/controller/articleSummary/SaveSummaryTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleOpinion/SaveOpinionTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceTest.java
Labels: 🔨 Refactor

#115 Fix: userId requestParam을 삭제
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/SummaryController.java
Labels: 🐞 BugFix

#117 Fix: SummaryRequestDto writer 재추가
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/SummaryRequestDto.java
Labels: 🐞 BugFix

#120 Feat/issue #116 소셜 로그인 Handler 추가
  src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/CustomAuthenticationFailureHandler.java
  src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/JwtAccessDeniedHandler.java
  src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/JwtAuthenticationEntryPoint.java
  src/main/java/com/knu/KnowcKKnowcK/config/WebSecurityConfig.java
  src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java
  src/main/java/com/knu/KnowcKKnowcK/dto/oauth/OAuthAttributes.java
  src/main/java/com/knu/KnowcKKnowcK/exception/ErrorCode.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/CustomOAuth2UerService.java
Labels: ✨ Feature

#122 Fix/issue #121 handler Fix
  src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/CustomAuthenticationFailureHandler.java
  src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/JwtAccessDeniedHandler.java
  src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/JwtAuthenticationEntryPoint.java
Labels: 🐞 BugFix

#124 Fix/issue #121 이메일 인증 response 수정
  src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java
  src/main/java/com/knu/KnowcKKnowcK/exception/ErrorCode.java
Labels: 🐞 BugFix

#119 Feat/issue #87 대시보드 조회 기능
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyDebateRoomController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyOpinionController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyProfileController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MySummaryController.java
  src/main/java/com/knu/KnowcKKnowcK/domain/Member.java
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/ProfileUpdateRequestDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DashboardResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MyDebateRoomResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/ProfileResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyDebateroomService.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyOpinionService.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyPageService.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MySummaryService.java
  src/test/java/com/knu/KnowcKKnowcK/service/myPage/MyPageServiceTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/myPage/MySummaryServiceTest.java
Labels: ✨ Feature

#125 Fix/issue #121 회원가입 formData 형식으로 수정
  src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/SignupRequestDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SignupResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/exception/ErrorCode.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/AccountService.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/MailService.java
Labels: 🐞 BugFix

#130 Fix/issue #129 구글 로그인 로직 수정
  src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/GoogleLoginRequestDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/GoogleLoginResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/exception/ErrorCode.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/AccountService.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/UserDetailsServiceImpl.java
Labels: 🐞 BugFix

#134 Fix: AI 요약 피드백 트랜잭션 이슈
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java
Labels: 🐞 BugFix

#137 Fix: 회원가입시 media type 에러 해결
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyProfileController.java
  src/main/java/com/knu/KnowcKKnowcK/domain/Member.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyPageService.java
Labels: :wrench: LogicFix

#136 Fix/issue #135
  src/main/java/com/knu/KnowcKKnowcK/domain/Opinion.java
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/OpinionRequestDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/article/ArticleListResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/exception/ErrorCode.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleOpinion/SaveOpinionServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleOpinion/SaveOpinionTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceTest.java
Labels: :wrench: LogicFix

#147 Fix/issue #143 회원가입/로그인 관련 오류 수정
  src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java
  src/main/java/com/knu/KnowcKKnowcK/dto/oauth/OAuthAttributes.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/AccountService.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/UserDetailsServiceImpl.java
Labels: 🐞 BugFix

#149 Feat: 문해력 진단 시 경험치 제공
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SummaryResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/enums/Score.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java
Labels: ✨ Feature

#153 Feat: 대시보드 DTO 경험치 필드 추가
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DashboardResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MySummaryResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyDebateroomService.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyPageService.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MySummaryService.java
Labels: ✨ Feature

#156 Refactor: Summary DTO 수정
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MySummaryResponseDto.java
Labels: 🔨 Refactor

#161 Refactor: Article 관련 클래스와 Summary 관련 클래스 패키지 분리
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/ArticleController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/OpinionController.java
  src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/SummaryController.java
  src/main/java/com/knu/KnowcKKnowcK/service/article/ArticleService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleOpinion/SaveOpinionService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryService.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceImpl.java
  src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryService.java
  src/main/java/com/knu/KnowcKKnowcK/service/opinion/OpinionService.java
  src/main/java/com/knu/KnowcKKnowcK/service/summary/SummaryFeedbackService.java
  src/main/java/com/knu/KnowcKKnowcK/service/summary/SummaryService.java
  src/test/java/com/knu/KnowcKKnowcK/controller/articleSummary/SaveSummaryTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/opinion/SaveOpinionTest.java
Labels: 🔨 Refactor

#164 Feat/issue #151 refreshToken
  src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/JwtAccessDeniedHandler.java
  src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/JwtAuthenticationEntryPoint.java
  src/main/java/com/knu/KnowcKKnowcK/config/WebSecurityConfig.java
  src/main/java/com/knu/KnowcKKnowcK/config/jwtConfig/JwtFilter.java
  src/main/java/com/knu/KnowcKKnowcK/config/jwtConfig/JwtSecurityConfig.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/GoogleLoginResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SigninResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/AccountService.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/MailService.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/TokenService.java
  src/main/java/com/knu/KnowcKKnowcK/utils/JwtUtil.java
  src/main/java/com/knu/KnowcKKnowcK/utils/RedisUtil.java
Labels: ✨ Feature

#171 Refactor/issue #168
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyProfileController.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DashboardResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/enums/Score.java
  src/main/java/com/knu/KnowcKKnowcK/repository/SummaryFeedbackRepository.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyPageService.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MySummaryService.java
  src/test/java/com/knu/KnowcKKnowcK/controller/myInfo/MyProfileControllerTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/myPage/MyPageServiceTest.java
  src/test/java/com/knu/KnowcKKnowcK/service/myPage/MySummaryServiceTest.java
Labels: :wrench: LogicFix, 🔨 Refactor

#174 Feat: 사용자 견해 개별 조회
  src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyOpinionController.java
  src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyOpinionService.java
Labels: ✨ Feature

#175 Refactor/issue #172 만료 토큰 갱신 로직 수정
  src/main/java/com/knu/KnowcKKnowcK/config/SecurityConfig.java
  src/main/java/com/knu/KnowcKKnowcK/config/jwtConfig/JwtFilter.java
  src/main/java/com/knu/KnowcKKnowcK/config/jwtConfig/JwtSecurityConfig.java
  src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java
  src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/NewAuthRequestDto.java
  src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/NewAuthResponseDto.java
  src/main/java/com/knu/KnowcKKnowcK/service/account/TokenService.java
Labels: 🔨 Refactor
